---
title: "Björninventering Västerbotten, 21 augusti-31 oktober 2019"
output: 
  flexdashboard::flex_dashboard:
    theme: readable
    logo: naturhistoriska-riksmuseet.png
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(readxl)
library(dplyr)
library(leaflet)
library(ggplot2)
library(wesanderson)
library(RColorBrewer)
source("gps_convert.R")
DNA <- read_excel("Data/Progress.xlsx")
names(DNA) <- c("Labnr","Streckkod", "DNA", "Kommentar")
bear <- read_excel("Data/rovbasedata.xlsx")
names(bear) <- c("Streckkod", "Art", "Datum", "Lat", "Long", "Provtyp", "Kommunnummer", "Kommun", "Lansnummer", "Lan")

bearmap <- base::merge(bear, DNA, by = "Streckkod", all.x = TRUE)
bearmap$DNA[is.na(bearmap$DNA)] <- 0
bearmap$Genotyp <- 0
bearmap$Genotyp[is.na(bearmap$Genotyp)] <- 0


bearmap <- gps_convert(data = bearmap, latitude = "Lat", longitude = "Long")

bearmap$code <- ifelse(bearmap$DNA + bearmap$Genotyp == 0, yes = "Registrerad", ifelse(bearmap$DNA + bearmap$Genotyp > 1.9, yes = "Genotypad", no = "DNA extraherat"))
bearmap$code <- factor(bearmap$code, levels = c("Registrerad", "DNA extraherat", "Genotypad"))
bearmap[order(as.character(bearmap$code), decreasing = FALSE),]

bearmap <- bearmap[bearmap$Streckkod != "SEP0156155",]
bearmap <- bearmap[bearmap$Streckkod != "SEP0154722",]

```

```{r}
getColor <- function(bearmap) {
  sapply(bearmap$code, function(code) {
  if(code == "Registrerad") {
    "gray"
  } else if(code == "DNA extraherat") {
    "orange"
  } else {
    "green"
  } })
}

icons <- awesomeIcons(
  icon = 'ios-close',
  iconColor = 'black',
  library = 'ion',
  markerColor = getColor(bearmap)
)
```



Column {data-width=650}
-----------------------------------------------------------------------

### Spillningsprover som inkommit till Naturhistoriska riksmuseet (NRM)

```{r}
# Mapping colors to the icons is done by eyeballing
pal <- colorFactor(c("dimgray", "orange", "limegreen") , domain = bearmap$code, ordered = TRUE)

leaflet(bearmap) %>%
      addProviderTiles(providers$OpenStreetMap,
                       options = providerTileOptions(noWrap = TRUE)) %>%
  addAwesomeMarkers(icon=icons, label=~as.character(Streckkod)) %>%
  addLegend( pal=pal, values = ~code, opacity=0.8, title = "Provstatus", position = "bottomleft")

```

Column {data-width=350}
-----------------------------------------------------------------------

### Antal insamlade prover per dag sedan inventeringsstarten den 21 Augusti

```{r}
ggplot(as.data.frame(bearmap)) + aes(x = Datum) + geom_bar() + scale_y_continuous(name = "Inkomna prover per dag")
```

### inkomna prover `r Sys.Date()`

```{r}
Bearsamples <- length(bearmap$code)
valueBox(Bearsamples,
	 icon = "fa-clipboard-check",
	 color = "gray")
```

### DNA extraherat

```{r}
dnaextract <- sum(bearmap$code == "DNA extraherat")
valueBox(dnaextract,
	 icon = "fa-dna",
	 color = "orange")

```


### bekräftad björn

```{r}
genotyped <- sum(bearmap$code == "Genotypad")
valueBox(genotyped,
	 icon = "fa-paw",
	 color = "green")
```